//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ttdsg.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TTDSG_DIALOG                102

#define IDR_MAINFRAME                   128
#define IDD_DIALOG_BINDWINDOW_DX           129

#define IDC_CHECK_BINDWINDOW_DX_DISPLAY_DX_2D 1000
#define IDC_CHECK_BINDWINDOW_DX_DISPLAY_DX_2D_2 1001
#define IDC_CHECK_BINDWINDOW_DX_DISPLAY_DX_3D 1002
#define IDC_CHECK_BINDWINDOW_DX_DISPLAY_DX_3D_8 1003
#define IDC_CHECK_BINDWINDOW_DX_DISPLAY_DX_OPENGL 1004
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_POSITION_LOCK_API 1005
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_POSITION_LOCK_MESSAGE 1006
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_FOCUS_INPUT_API 1007
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_FOCUS_INPUT_MESSAGE 1008
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_CLIP_LOCK_API 1009
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_INPUT_LOCK_API 1010
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_STATE_API 1011
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_STATE_MESSAGE 1012
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_API 1013
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_CURSOR 1014
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_RAW_INPUT 1015
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_INPUT_LOCK_API2 1016
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_INPUT_LOCK_API3 1017
#define IDC_CHECK_BINDWINDOW_DX_KEYBOARD_DX_INPUT_LOCK_API 1018
#define IDC_CHECK_BINDWINDOW_DX_KEYBOARD_DX_STATE_API 1019
#define IDC_CHECK_BINDWINDOW_DX_KEYBOARD_DX_API 1020
#define IDC_CHECK_BINDWINDOW_DX_KEYBOARD_DX_RAW_INPUT 1021
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_ACTIVE_API 1022
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_ACTIVE_MESSAGE 1023
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_DISABLE_WINDOW_POSITION 1024
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_DISABLE_WINDOW_SIZE 1025
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_DISABLE_WINDOW_MINMAX 1026
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_FAKE_WINDOW_MIN 1027
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_HIDE_DLL 1028
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_ACTIVE_API2 1029
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_INPUT_IME 1030
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_GRAPHIC_PROTECT 1031
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_DISABLE_WINDOW_SHOW 1032
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_ANTI_API 1033
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_MEMORY 1034
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_KM_PROTECT 1035
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_PREVENT_BLOCK 1036
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_ORI_PROC 1037
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_DOWN_CPU 1038
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_FOCUS_MESSAGE 1039

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
