//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ttdsg.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TTDSG_DIALOG                102
#define IDR_HTML_BINDWINDOWDLG          103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_BINDWINDOW_DX        129
#define IDD_DIALOG_BINDWINDOW           130
#define IDD_DIALOG_REGISTER             131
#define IDD_DIALOG_LOGIN	            132
#define IDD_DIALOG_RESETPWD             133
#define IDD_DIALOG_RECHARGE             134
#define IDD_DIALOG_USERINFO             135

#define IDC_CHECK_BINDWINDOW_DX_DISPLAY_DX_2D 1000
#define IDC_CHECK_BINDWINDOW_DX_DISPLAY_DX_2D_2 1001
#define IDC_CHECK_BINDWINDOW_DX_DISPLAY_DX_3D 1002
#define IDC_CHECK_BINDWINDOW_DX_DISPLAY_DX_3D_8 1003
#define IDC_CHECK_BINDWINDOW_DX_DISPLAY_DX_OPENGL 1004
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_POSITION_LOCK_API 1005
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_POSITION_LOCK_MESSAGE 1006
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_FOCUS_INPUT_API 1007
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_FOCUS_INPUT_MESSAGE 1008
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_CLIP_LOCK_API 1009
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_INPUT_LOCK_API 1010
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_STATE_API 1011
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_STATE_MESSAGE 1012
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_API 1013
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_CURSOR 1014
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_RAW_INPUT 1015
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_INPUT_LOCK_API2 1016
#define IDC_CHECK_BINDWINDOW_DX_MOUSE_DX_INPUT_LOCK_API3 1017
#define IDC_CHECK_BINDWINDOW_DX_KEYBOARD_DX_INPUT_LOCK_API 1018
#define IDC_CHECK_BINDWINDOW_DX_KEYBOARD_DX_STATE_API 1019
#define IDC_CHECK_BINDWINDOW_DX_KEYBOARD_DX_API 1020
#define IDC_CHECK_BINDWINDOW_DX_KEYBOARD_DX_RAW_INPUT 1021
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_ACTIVE_API 1022
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_ACTIVE_MESSAGE 1023
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_DISABLE_WINDOW_POSITION 1024
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_DISABLE_WINDOW_SIZE 1025
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_DISABLE_WINDOW_MINMAX 1026
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_FAKE_WINDOW_MIN 1027
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_HIDE_DLL 1028
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_ACTIVE_API2 1029
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_INPUT_IME 1030
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_GRAPHIC_PROTECT 1031
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_DISABLE_WINDOW_SHOW 1032
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_ANTI_API 1033
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_MEMORY 1034
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_KM_PROTECT 1035
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_PREVENT_BLOCK 1036
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_ORI_PROC 1037
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_DOWN_CPU 1038
#define IDC_CHECK_BINDWINDOW_DX_PUBLIC_DX_FOCUS_MESSAGE 1039

#define IDC_RADIO_BINDWINDOW_BINDWINDOW_NORMAL 1100
#define IDC_RADIO_BINDWINDOW_BINDWINDOW_GDI 1101
#define IDC_RADIO_BINDWINDOW_BINDWINDOW_GDI2 1102
#define IDC_RADIO_BINDWINDOW_BINDWINDOW_DX2 1103
#define IDC_RADIO_BINDWINDOW_BINDWINDOW_DX3 1104
#define IDC_RADIO_BINDWINDOW_BINDWINDOW_DX 1105
#define IDC_CHECK_BINDWINDOW_BINDPUBIC_DX 1106
#define IDC_RADIO_BINDWINDOW_BINDMOUSE_NORMAL 1107
#define IDC_RADIO_BINDWINDOW_BINDMOUSE_WINDOWS3 1108
#define IDC_RADIO_BINDWINDOW_BINDMOUSE_WINDOWS 1109
#define IDC_RADIO_BINDWINDOW_BINDMOUSE_DX 1110
#define IDC_RADIO_BINDWINDOW_BINDKEYBOARD_NORMAL 1111
#define IDC_RADIO_BINDWINDOW_BINDKEYBOARD_DX 1112
#define IDC_RADIO_BINDWINDOW_BINDKEYBOARD_WINDOWS 1113
#define IDC_RADIO_BINDWINDOW_BINDMODEL_0 1114
#define IDC_RADIO_BINDWINDOW_BINDMODEL_1 1115
#define IDC_RADIO_BINDWINDOW_BINDMODEL_2 1116
#define IDC_RADIO_BINDWINDOW_BINDMODEL_3 1117
#define IDC_RADIO_BINDWINDOW_BINDMODEL_4 1118
#define IDC_RADIO_BINDWINDOW_BINDMODEL_5 1119
#define IDC_RADIO_BINDWINDOW_BINDMODEL_6 1120
#define IDC_RADIO_BINDWINDOW_BINDMODEL_7 1121
#define IDC_RADIO_BINDWINDOW_BINDMODEL_101 1122
#define IDC_RADIO_BINDWINDOW_BINDMODEL_103 1123
#define IDC_RADIO_BINDWINDOW_BINDMODEL_AUTO 1124

#define IDC_EDIT_REGISTER_USERNAME 1200
#define IDC_EDIT_REGISTER_PASSWORD 1201
#define IDC_EDIT_REGISTER_REPASSWORD 1202
#define IDC_EDIT_REGISTER_EMAIL 1203
#define IDC_EDIT_REGISTER_TELEPHONE 1204
#define IDC_BUTTON_REGISTER_REGISTER 1205
#define IDC_BUTTON_REGISTER_RESETINFO 1206

#define IDC_BUTTON_LOGIN_LOGIN 1300
#define IDC_BUTTON_LOGIN_REGISTER 1301
#define IDC_BUTTON_LOGIN_RECHARGE 1302
#define IDC_EDIT_LOGIN_USERNAME 1303
#define IDC_EDIT_LOGIN_PASSWORD 1304
#define IDC_CHECK_LOGIN_MEMORIZEPASSWORD 1305
#define IDC_BUTTON_LOGIN_FORGETPWD 1306

#define IDC_EDIT_RESETPWD_USERNAME 1400
#define IDC_EDIT_RESETPWD_EMAIL 1401
#define IDC_BUTTON_RESETPWD_OK 1402
#define IDC_STATIC_RESETPWD_EMAIL 1403
#define IDC_STATIC_RESETPWD_OLDPWD 1404
#define IDC_STATIC_RESETPWD_NEWPWD 1405
#define IDC_STATIC_RESETPWD_NEWPWD1 1406
#define IDC_EDIT_RESETPWD_OLDPWD 1407
#define IDC_EDIT_RESETPWD_NEWPWD 1408
#define IDC_EDIT_RESETPWD_NEWPWD1 1409

#define IDC_EDIT_RECHARGE_USERNAME 1500
#define IDC_BUTTON_RECHARGE_RECHARGE 1501
#define IDC_EDIT_RECHARGE_CARDPWD 1502
#define IDC_EDIT_RECHARGE_RECOMMENDUSERNAME 1503

#define IDC_STATIC_USERINFO_USERNAME 1600
#define IDC_STATIC_USERINFO_EXPIRED 1601
#define IDC_EDIT_USERINFO_EMAIL 1602
#define IDC_EDIT_USERINFO_CARDPWD 1603
#define IDC_EDIT_USERINFO_RECOMMENDUSER 1604
#define IDC_BUTTON_USERINFO_PWDMODIFY 1605
#define IDC_BUTTON_USERINFO_RECHARGE 1606
#define IDC_BUTTON_USERINFO_BINGINGMAC 1607
#define IDC_STATIC_USERINFO_EMAIL 1608
#define IDC_EDIT_USERINFO_NEWPWD 1609
#define IDC_EDIT_USERINFO_NEWPWD1 1610
#define IDC_STATIC_USERINFO_NEWPWD 1611
#define IDC_STATIC_USERINFO_NEWPWD1 1612

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1700
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
